---
Name: 'asset-icons'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - restruct/silverstripe-asset_icons:client/js/asset-icons.js
  extra_requirements_css:
    - restruct/silverstripe-asset_icons:client/css/asset-icons.css